name: Code Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '44 15 * * 5'

permissions:
  contents: read

jobs:
  trivy:
    name: Run Trivy scan report
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Run Trivy vulnerability scanner (Table)
        uses: aquasecurity/trivy-action@5681af892cd0f4997658e2bacc62bd0a894cf564 # v0.27.0
        with:
          scan-type: 'config'
          trivy-config: '.github/trivy.yml'
          
      - name: Run Trivy vulnerability scanner (Sarif)
        if: success() || failure()
        uses: aquasecurity/trivy-action@5681af892cd0f4997658e2bacc62bd0a894cf564 # v0.27.0
        with:
          scan-type: 'config'
          severity: 'MEDIUM,CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
  
      - name: Upload Trivy scan results to GitHub Security tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@f779452ac5af1c261dce0346a8f964149f49322b # v3.26.13
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Publish Trivy Output to Summary
        if: success() || failure()
        run: |
          if [[ -s trivy.txt ]]; then
            {
              echo "### Security Output"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```terraform'
              cat trivy.txt
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi
